# Generated by Django 5.0.4 on 2024-04-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='users/default_profile_image.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
