# Generated by Django 5.0.4 on 2024-05-02 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_category_slug_alter_question_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('DF', 'Черновик'), ('PB', 'Опубликован'), ('BN', 'В бане')], default='DF', max_length=2),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='questions_q_created_7d8295_idx'),
        ),
    ]
