# Generated by Django 5.0.4 on 2024-05-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='votes',
            new_name='votes_count',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='votes',
            new_name='votes_count',
        ),
    ]
