# Generated by Django 5.0.4 on 2024-05-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_rename_votes_answer_votes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers_count',
            field=models.IntegerField(default=0),
        ),
    ]
