

services:
  nginx:
    image: nginx:stable-alpine
    ports: 
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - db
      - backend 
      - redis
    networks:
      - dev

  db:
    image: postgres:15-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - "5439:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - dev

  redis:
    image: redis:alpine
    ports:
      - "6390:6379"
    networks:
      - dev

  backend: 
    build: . 
    entrypoint: /entrypoint.sh
    ports: 
      - "8000:8000"
      - "1212:5555"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - dev

networks:
  dev:
