version: '3'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - "5439:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 
 

  redis:
    image: redis:alpine
    ports:
      - "6390:6379" 


  backend: 
    build: . 
    entrypoint: /entrypoint.sh
    ports: 
      - "8000:8000"
      - "1212:5555"
    depends_on:
      - db
      - redis
    env_file:
      - .env

    
