version: '3'

services:
  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
    ports:
      - "5439:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - "6390:6379" 

networks:
  db_net: