# Generated by Django 5.0.4 on 2024-05-14 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_rename_votes_answer_votes_count_and_more'),
        ('votes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionVote',
            new_name='VoteForQuestion',
        ),
    ]
